### PR TITLE
Fixes #22 Invalid generic import and Primitive import while field is required in constructor.

### LINKED ISSUE #22: Invalid generic import and Primitive import while field is required in constructor.
There is a unexpected import while generic parameter is in constructor:

```
package com.example.model;

import java.util.List;

import info.ludwikowski.fluentbuilder.annotation.GenerateBuilder;

@GenerateBuilder
public class Foo {

    private String var1;
    private List<Bar> var2;

    public Foo(String var1, List<Bar> var2) {
        this.var1 = var1;
        this.var2 = var2;
    }

    public String getVar1() {
        return var1;
    }

    public List<Bar> getVar2() {
        return var2;
    }
}
```

And generic class definition:
```
package com.example.model;

public class Bar {

    private String var1;

    public Bar(String var1) {
        this.var1 = var1;
    }

    public String getVar1() {
        return var1;
    }
}
```

Invalid builder for Foo is generated:
```
package com.example.model;

import info.ludwikowski.fluentbuilder.common.AbstractBuilderFactory;
import java.util.List<com.example.model.Bar>;


/**
 * Fluent builder for Foo.
 * Don't hesitate to put your custom methods here.
 */
public abstract class FooBudowniczy extends AbstrakcyjnyFooBudowniczy<FooBudowniczy> {

	public static FooBudowniczy foo(String var1, List<Bar> var2){
		return AbstractBuilderFactory.createImplementation(FooBudowniczy.class, var1, var2);
	}
}
```

In import section the generic parameter is redundant:
`import java.util.List<com.example.model.Bar>;`

### PR DESCRIPTION
**Pull request by athlan**
Fixes: https://github.com/aludwiko/fluentbuilder/issues/22

### CODE REVIEW

File: src/test/java/info/ludwikowski/fluentbuilder/sample/types/GenericType.java [hunk 1]
```diff
@@ -0,0 +1,5 @@
+package info.ludwikowski.fluentbuilder.sample.types;
```
Comment (aludwiko) [inline src/test/java/info/ludwikowski/fluentbuilder/sample/types/GenericType.java]: I would create `generics` package instead of `types` and put there: `GenericType`, `SimpleType`, `ClassWithGenericTypes`, `ClassWithoutDefaultConstructorWithGenericTypes`

File: src/test/resources/info/ludwikowski/fluentbuilder/generator/BuildersForClassWithoutDefaultConstructorWithGenericTypes [hunk 2]
```diff
@@ -0,0 +1,46 @@
+package info.ludwikowski.fluentbuilder.sample.withoutdefaultconstructor;
```
Comment (aludwiko) [inline src/test/resources/info/ludwikowski/fluentbuilder/generator/BuildersForClassWithoutDefaultConstructorWithGenericTypes]: `withoutdefaultconstructor` -> `generics`

**Review by aludwiko — CHANGES_REQUESTED** [review]

**Comment by athlan** [comment]
@aludwiko your suggestions has been included in 9f704455c6dd734f361b4fed54b3cddff7181f49.
